### ISSUE TITLE
[questions] about evaluation script

### ISSUE THREAD

**Issue by ypc-stu** [tavo91/NER-WNUT17#3]
Hi
I enter into  ./predictions/    Run the evaluation script, but I got some errors
The command I entered is: ./eval.sh crfsuite.tsv
![图片](https://user-images.githubusercontent.com/48792547/60346314-7a51f080-99ed-11e9-88c3-0895f1300a28.png)

What was the cause of the mistakes?
Look forward to your replies.

**Comment by himkt** [comment]
What happen if you use Python2.x or add "from functools import reduce" in wnuteval.py?

related: https://stackoverflow.com/questions/8689184/nameerror-name-reduce-is-not-defined-in-python

**Comment by himkt** [comment]
@ypc-stu

What happen if you use Python2.x or add "from functools import reduce" in wnuteval.py?

related: https://stackoverflow.com/questions/8689184/nameerror-name-reduce-is-not-defined-in-python

**Comment by ypc-stu** [comment]
@himkt 
thank you for your replies,
I have solved this problem.yes,this problem is the python version, Reduce was available in Python 2 by default, but in Python 3 it was moved to functools.
